# .safepush.yml

ignore_paths:
  - ".safepush.yml"
  - "docs/**"
  - "tests/**"

ignore_patterns:
  # Exact or regex-style patterns for known-safe values
  - "AKIA_NOT_REAL_1234567890ABCDE1"       # example fake AWS key
  - "dummy_(key|secret)_.*"

ignore_lines_with:
  - "# safepush: ignore"

allowlist_hashes:
  # Example:
  # - "sha256:<hash-of-known-safe-secret>"
  # Used when you never want a specific value flagged, even if moved.
  # Leave empty or omit if not needed.

# High-level policy profile:
#   strict   -> block on LOW/MEDIUM/HIGH
#   balanced -> block on MEDIUM/HIGH
#   relaxed  -> block on HIGH only
policy_profile: "balanced"

# Optional explicit override:
# If you set this, it *overrides* the profile.
# block_severity: "HIGH"