# .safepush.yml

ignore_paths:
  - ".safepush.yml"
  - "docs/**"
  - "tests/**"

ignore_patterns:
  # Exact or regex-style patterns for known-safe values
  - "AKIA_NOT_REAL_1234567890ABCDE1"       # example fake AWS key
  - "dummy_(key|secret)_.*"

ignore_lines_with:
  - "# safepush: ignore"

allowlist_hashes:
  # Example:
  # - "sha256:<hash-of-known-safe-secret>"
  # Used when you never want a specific value flagged, even if moved.
  # Leave empty or omit if not needed.

# New: configure minimum severity that BLOCKS commits/CI.
# Options: "LOW", "MEDIUM", "HIGH"
block_severity: "HIGH"
